# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

driverName: hyperv.csi.fireflycons.io

replicaCount: 1

image:
  repository: fireflycons/hyperv-csi-plugin
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Settings for the CSI controller
controller:
  executable: hyperv-csi-plugin
  # Directory to store gRPC unix socket
  endpointDirectory: /var/lib/csi/sockets/pluginproxy
  # Address of the khyperv-provider Windows service
  serviceUrl: ""
  # API key to access Windows Service
  apiKey: ""
  # Self-signed CA certificate in PEM format. Pass with --set-file
  caCert: ""
  logLevel: 4 # info
  # TODO - remove when support is added
  supportsSnapshot: false

# This sets the versions of the CSI co-located containers on registry.k8s.io/sig-storage
csiVersions:
  provisioner: v5.2.0
  attacher: v4.8.1
  snapshotter: v8.2.0
  resizer: v1.13.2
  registrar: v2.13.0

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# The following apply to the controller workload only.
# Node workload is a daemonset and must be on all nodes.
nodeSelector: {}

tolerations: []

affinity: {}
